import { Icon } from "@/components/shared/icon";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { requireCurrentUser } from "@/lib/auth";

export default async function SettingsPage() {
  const user = await requireCurrentUser();
  const [firstName = "", ...remainingNames] = user.name.split(" ");
  const lastName = remainingNames.join(" ");
  const isDevelopment = process.env.NODE_ENV === "development";
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  return <><PageHeader eyebrow="Preferences" title="Settings" description="Manage your profile, notifications, and security preferences." /><div className="settings-grid"><Card className="settings-card"><div className="settings-card-heading"><span><Icon name="users" /></span><div><h2>Personal information</h2><p>Used for your workspace and application correspondence.</p></div></div><div className="settings-form"><div className="form-row"><label>First name<Input defaultValue={firstName} /></label><label>Last name<Input defaultValue={lastName} /></label></div><label>Email address<Input defaultValue={user.email} type="email" /></label><label>Phone number<Input placeholder="Add a phone number" /></label><Button variant="outline">Save profile</Button></div></Card><div className="settings-stack"><Card className="settings-card compact-settings"><div className="settings-card-heading"><span><Icon name="bell" /></span><div><h2>Notifications</h2><p>Application updates and review alerts.</p></div></div><label className="toggle-row"><span><strong>Application updates</strong><small>Email me when a status changes</small></span><input type="checkbox" defaultChecked /></label><label className="toggle-row"><span><strong>Review reminders</strong><small>Remind me about missing documents</small></span><input type="checkbox" defaultChecked /></label></Card><Card className="settings-card compact-settings"><div className="settings-card-heading"><span><Icon name="lock" /></span><div><h2>Security</h2><p>Password and active sessions.</p></div></div><button className="settings-link">Change password <Icon name="arrow" /></button><button className="settings-link">Manage active sessions <Icon name="arrow" /></button></Card>{isDevelopment && <Card className="settings-card development-health-card"><div className="settings-card-heading"><span><Icon name="audit" /></span><div><h2>Local development health</h2><p>Session and environment details for troubleshooting.</p></div></div><div className="settings-form"><label>Logged-in user<Input value={`${user.name} (${user.email})`} readOnly /></label><label>Application URL<Input value={appUrl} readOnly /></label><label>Authentication session<Input value="Active — server session verified" readOnly /></label><div className="settings-debug-help"><strong>Local troubleshooting</strong><ol><li>Run <code>pnpm dev:infra</code> for PostgreSQL and Redis.</li><li>Run <code>pnpm dev:setup</code> to apply Prisma migrations.</li><li>Run <code>pnpm dev</code> for web, worker, and OCR services.</li></ol></div></div></Card>}</div></div></>;
}
