import { Icon } from "@/components/shared/icon";
import { PageHeader } from "@/components/shared/page-header";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function SettingsPage() {
  return <><PageHeader eyebrow="Preferences" title="Settings" description="Manage your profile, notifications, and security preferences." /><div className="settings-grid"><Card className="settings-card"><div className="settings-card-heading"><span><Icon name="users" /></span><div><h2>Personal information</h2><p>Used for your workspace and application correspondence.</p></div></div><div className="settings-form"><div className="form-row"><label>First name<Input defaultValue="Alex" /></label><label>Last name<Input defaultValue="Morgan" /></label></div><label>Email address<Input defaultValue="alex@example.com" type="email" /></label><label>Phone number<Input defaultValue="+44 7700 900123" /></label><Button variant="outline">Save profile</Button></div></Card><div className="settings-stack"><Card className="settings-card compact-settings"><div className="settings-card-heading"><span><Icon name="bell" /></span><div><h2>Notifications</h2><p>Application updates and review alerts.</p></div></div><label className="toggle-row"><span><strong>Application updates</strong><small>Email me when a status changes</small></span><input type="checkbox" defaultChecked /></label><label className="toggle-row"><span><strong>Review reminders</strong><small>Remind me about missing documents</small></span><input type="checkbox" defaultChecked /></label></Card><Card className="settings-card compact-settings"><div className="settings-card-heading"><span><Icon name="lock" /></span><div><h2>Security</h2><p>Password and active sessions.</p></div></div><button className="settings-link">Change password <Icon name="arrow" /></button><button className="settings-link">Manage active sessions <Icon name="arrow" /></button></Card></div></div></>;
}
